on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_changes:
    name: release updated board definitions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip
    - name: Run release creator
      run: |
        python create_release.py
